###############################################################################
# core - the rotation engine
#
# Deploy this alone and you get expiry-driven rotation: a schedule, a runbook and
# the permissions it needs. Everything else in this repository is optional and
# layers on top by setting automation variables that the runbook reads at start-up.
###############################################################################

locals {
  runbook_name = "Invoke-CredentialRotation"

  # Written by this module. The observability and rotate-on-access modules add
  # their own CR_* variables; the runbook resolves parameter, then variable, then
  # default, so an undeployed module simply leaves the feature off.
  #
  # The automation variable resource rejects empty strings, and an absent variable is
  # exactly how the runbook expects to be told "use the default" - so the optional
  # entry is merged in rather than written empty.
  #
  # It has to be merge() rather than a filtered comprehension: several values here are
  # only known after apply, and a comprehension whose condition reads them makes the
  # map's *keys* unknown at plan time, which for_each cannot work with.
  variables = merge(
    {
      CR_VaultName                = var.key_vault_name
      CR_ThresholdDays            = tostring(var.threshold_days)
      CR_ValidityDays             = tostring(var.validity_days)
      CR_EnableTagName            = var.enable_tag_name
      CR_EnableTagValue           = var.enable_tag_value
      CR_SecretNameTemplate       = var.secret_name_template
      CR_AutomationAccountName    = azurerm_automation_account.this.name
      CR_AutomationResourceGroup  = var.resource_group_name
      CR_AutomationSubscriptionId = data.azurerm_client_config.current.subscription_id
      CR_DryRun                   = tostring(var.dry_run)
    },
    length(var.target_subscription_ids) > 0
    ? { CR_SubscriptionId = join(",", var.target_subscription_ids) }
    : {}
  )
}

data "azurerm_client_config" "current" {}

resource "azurerm_automation_account" "this" {
  name                = var.automation_account_name
  resource_group_name = var.resource_group_name
  location            = var.location
  sku_name            = "Basic"
  tags                = var.tags

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_automation_runbook" "rotation" {
  name                    = local.runbook_name
  resource_group_name     = var.resource_group_name
  location                = var.location
  automation_account_name = azurerm_automation_account.this.name

  runbook_type = "PowerShell72"
  log_verbose  = var.log_verbose
  log_progress = false
  description  = "Reconciles Azure VM credentials against their Key Vault expiry dates."
  tags         = var.tags

  # Generated by build/Build-Runbook.ps1 and committed, so no build step is needed to
  # deploy. It lives inside this module rather than in a top-level dist/, because
  # file() can only read files that are part of the module's own source - a path that
  # escapes the module directory breaks as soon as the module is consumed from a git
  # URL. CI verifies the artefact matches the sources.
  content = var.runbook_content != null ? var.runbook_content : file("${path.module}/runbook/Invoke-CredentialRotation.ps1")
}

resource "azurerm_automation_variable_string" "settings" {
  for_each = local.variables

  name                    = each.key
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.this.name
  value                   = each.value
  encrypted               = false
}

###############################################################################
# schedule
#
# Automation schedules cannot run more often than hourly. The interval sets the
# worst-case delay between a credential being marked for rotation and it actually
# being replaced, which matters most for access-driven rotation: total exposure is
# roughly the grace period plus this interval.
#
# Azure requires a start time at least five minutes out, so it is offset from apply
# time rather than pinned to a fixed clock.
###############################################################################

resource "time_offset" "schedule_start" {
  offset_minutes = 15
}

resource "azurerm_automation_schedule" "recurring" {
  name                    = "${local.runbook_name}-every-${var.schedule_interval_hours}h"
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.this.name

  frequency   = "Hour"
  interval    = var.schedule_interval_hours
  timezone    = var.schedule_timezone
  start_time  = time_offset.schedule_start.rfc3339
  description = "Reconciliation pass. Also the retry mechanism: anything skipped or failed is picked up next run."
}

resource "azurerm_automation_job_schedule" "recurring" {
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.this.name
  runbook_name            = azurerm_automation_runbook.rotation.name
  schedule_name           = azurerm_automation_schedule.recurring.name

  # No parameters on the link. Automation ignores a PUT on a link that already exists, so a
  # value here could never be changed by a later apply; dry_run lands in CR_DryRun instead.
}

###############################################################################
# permissions
#
# Least privilege, but note what "Virtual Machine Contributor" allows: it can
# install extensions, which is how the credential reaches the guest, and that is
# effectively code execution as SYSTEM or root on every VM in scope. Keep the scope
# as narrow as you can - a resource group, not a subscription, where possible.
###############################################################################

resource "azurerm_role_assignment" "key_vault" {
  scope                = var.key_vault_id
  principal_id         = azurerm_automation_account.this.identity[0].principal_id
  role_definition_name = "Key Vault Secrets Officer"
  description          = "Read secret metadata, write rotated credentials, update expiry dates."
}

# The runbook checks whether another instance of itself is already running before it
# starts work. Without this role that check throws, gets caught, and silently protects
# nothing - which is exactly how it behaved on the first live run.
resource "azurerm_role_assignment" "job_reader" {
  scope                = azurerm_automation_account.this.id
  principal_id         = azurerm_automation_account.this.identity[0].principal_id
  role_definition_name = "Automation Job Operator"
  description          = "Let the runbook see whether another instance of itself is already running."
}

# count rather than for_each: scopes are commonly resource groups created in the
# same apply, so their IDs are unknown at plan time. for_each cannot build its keys
# from unknown values, which makes the module unusable in exactly the case it is
# most often used in.
resource "azurerm_role_assignment" "compute" {
  count = length(var.vm_scopes)

  scope                = var.vm_scopes[count.index]
  principal_id         = azurerm_automation_account.this.identity[0].principal_id
  role_definition_name = "Virtual Machine Contributor"
  description          = "Apply credentials through the VMAccess extension."
}
