###############################################################################
# core - the rotation engine
#
# Deploy this alone and you get expiry-driven rotation: a schedule, a runbook and
# the permissions it needs. Everything else in this repository is optional and
# layers on top by setting automation variables that the runbook reads at start-up.
###############################################################################

locals {
  runbook_name = "Invoke-CredentialRotation"

  # Written by this module. The observability and rotate-on-access modules add
  # their own CR_* variables; the runbook resolves parameter, then variable, then
  # default, so an undeployed module simply leaves the feature off.
  variables = {
    CR_VaultName               = var.key_vault_name
    CR_ThresholdDays           = tostring(var.threshold_days)
    CR_ValidityDays            = tostring(var.validity_days)
    CR_EnableTagName           = var.enable_tag_name
    CR_EnableTagValue          = var.enable_tag_value
    CR_AutomationAccountName   = azurerm_automation_account.this.name
    CR_AutomationResourceGroup = var.resource_group_name
    CR_SubscriptionId          = join(",", var.target_subscription_ids)
  }
}

resource "azurerm_automation_account" "this" {
  name                = var.automation_account_name
  resource_group_name = var.resource_group_name
  location            = var.location
  sku_name            = "Basic"
  tags                = var.tags

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_automation_runbook" "rotation" {
  name                    = local.runbook_name
  resource_group_name     = var.resource_group_name
  location                = var.location
  automation_account_name = azurerm_automation_account.this.name

  runbook_type = "PowerShell72"
  log_verbose  = var.log_verbose
  log_progress = false
  description  = "Reconciles Azure VM credentials against their Key Vault expiry dates."
  tags         = var.tags

  # Generated by build/Build-Runbook.ps1 and committed, so no build step is needed
  # to deploy. CI verifies the artefact matches the sources.
  content = var.runbook_content != null ? var.runbook_content : file("${path.module}/../../../dist/Invoke-CredentialRotation.runbook.ps1")
}

resource "azurerm_automation_variable_string" "settings" {
  for_each = local.variables

  name                    = each.key
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.this.name
  value                   = each.value
  encrypted               = false
}

###############################################################################
# schedule
#
# Automation schedules cannot run more often than hourly. The interval sets the
# worst-case delay between a credential being marked for rotation and it actually
# being replaced, which matters most for access-driven rotation: total exposure is
# roughly the grace period plus this interval.
#
# Azure requires a start time at least five minutes out, so it is offset from apply
# time rather than pinned to a fixed clock.
###############################################################################

resource "time_offset" "schedule_start" {
  offset_minutes = 15
}

resource "azurerm_automation_schedule" "recurring" {
  name                    = "${local.runbook_name}-every-${var.schedule_interval_hours}h"
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.this.name

  frequency   = "Hour"
  interval    = var.schedule_interval_hours
  timezone    = var.schedule_timezone
  start_time  = time_offset.schedule_start.rfc3339
  description = "Reconciliation pass. Also the retry mechanism: anything skipped or failed is picked up next run."
}

resource "azurerm_automation_job_schedule" "recurring" {
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.this.name
  runbook_name            = azurerm_automation_runbook.rotation.name
  schedule_name           = azurerm_automation_schedule.recurring.name

  parameters = {
    dryrun = tostring(var.dry_run)
  }
}

###############################################################################
# permissions
#
# Least privilege, but note what "Virtual Machine Contributor" allows: it can
# install extensions, which is how the credential reaches the guest, and that is
# effectively code execution as SYSTEM or root on every VM in scope. Keep the scope
# as narrow as you can - a resource group, not a subscription, where possible.
###############################################################################

resource "azurerm_role_assignment" "key_vault" {
  scope                = var.key_vault_id
  principal_id         = azurerm_automation_account.this.identity[0].principal_id
  role_definition_name = "Key Vault Secrets Officer"
  description          = "Read secret metadata, write rotated credentials, update expiry dates."
}

resource "azurerm_role_assignment" "compute" {
  for_each = toset(var.vm_scopes)

  scope                = each.value
  principal_id         = azurerm_automation_account.this.identity[0].principal_id
  role_definition_name = "Virtual Machine Contributor"
  description          = "Apply credentials through the VMAccess extension."
}
